# Generated by Django 5.1.7 on 2025-03-25 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakem_adi', models.CharField(max_length=100)),
                ('yorum', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
    ]
