# Generated by Django 5.1.7 on 2025-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0002_degerlendirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='anonim_dosya',
            field=models.FileField(blank=True, null=True, upload_to='anonim/'),
        ),
    ]
