# Generated by Django 5.1.7 on 2025-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_makale_anonim_dosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='mesaj',
            field=models.TextField(blank=True, null=True),
        ),
    ]
