# Generated by Django 5.1.7 on 2025-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0004_makale_mesaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
