# Generated by Django 5.1.7 on 2025-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_makale_yorumlu_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='final/'),
        ),
    ]
