# Generated by Django 5.1.7 on 2025-03-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0007_makale_final_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='atandigi_hakem',
            field=models.CharField(blank=True, choices=[('hakem1', 'Hakem 1'), ('hakem2', 'Hakem 2'), ('hakem3', 'Hakem 3')], max_length=10, null=True),
        ),
    ]
