# Generated by Django 5.1.7 on 2025-03-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0008_makale_atandigi_hakem'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='log_editore_gelis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='log_hakem_cevap',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='log_hakeme_atis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='log_yayim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
