# Generated by Django 5.1.7 on 2025-03-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0009_makale_log_editore_gelis_makale_log_hakem_cevap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderen', models.CharField(max_length=100)),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='makale.makale')),
            ],
        ),
    ]
