# Generated by Django 5.1.7 on 2025-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0010_mesaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='gonderen',
            field=models.CharField(choices=[('yazar', 'Yazar'), ('editor', 'Editör')], max_length=10),
        ),
    ]
