# Generated by Django 5.1.7 on 2025-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0011_alter_mesaj_gonderen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='gonderen',
        ),
        migrations.AddField(
            model_name='mesaj',
            name='cevap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
