# Generated by Django 5.1.7 on 2025-03-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0012_remove_mesaj_gonderen_mesaj_cevap'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='final_pdf_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='pdf_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='yorumlu_pdf_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
