# Generated by Django 5.1.7 on 2025-03-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0013_makale_final_pdf_hash_makale_pdf_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='takip_numarasi',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
