# Generated by Django 5.1.7 on 2025-03-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0014_alter_makale_takip_numarasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='revize_hakeme_atildi',
            field=models.BooleanField(default=False),
        ),
    ]
