# Generated by Django 5.1.7 on 2025-03-28 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0015_makale_revize_hakeme_atildi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='takip_numarasi',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
