# Generated by Django 5.1.7 on 2025-03-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0016_alter_makale_takip_numarasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='cevap',
        ),
        migrations.AddField(
            model_name='mesaj',
            name='okundu',
            field=models.BooleanField(default=False),
        ),
    ]
