# Generated by Django 5.1.7 on 2025-03-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0017_remove_mesaj_cevap_mesaj_okundu'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='mesaj_gonderen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
